import 'package:hive/hive.dart';
import 'package:zonka_feedback/services/hive/hive_type_id.dart';

part 'udpate_survey_res_model.g.dart'; // This will be generated by Hive

@HiveType(typeId: HiveTypeId.updateResSurveyId) // Define a unique typeId for this model
class UpdateSurveyResModel extends HiveObject {
  @HiveField(0)
  final bool updatesAvailable;

  @HiveField(1)
  final bool isDeleted;

  @HiveField(2)
  final String surveyId;

  UpdateSurveyResModel({
    required this.updatesAvailable,
    required this.isDeleted,
    required this.surveyId,
  });

  // Factory constructor to create an instance from JSON
  factory UpdateSurveyResModel.fromJson(Map<String, dynamic> json) {
    return UpdateSurveyResModel(
      updatesAvailable: json['updatesAvailable'] as bool,
      isDeleted: json['isDeleted'] as bool,
      surveyId: json['surveyId'] as String,
    );
  }

  // Convert the model to a JSON object
  Map<String, dynamic> toJson() {
    return {
      'updatesAvailable': updatesAvailable,
      'isDeleted': isDeleted,
      'surveyId': surveyId,
    };
  }
}

