import 'package:hive/hive.dart';
import 'package:zonka_feedback/services/hive/hive_type_id.dart';

part 'filed_translation_model.g.dart'; // This file will be generated by Hive


@HiveType(typeId: HiveTypeId.filedTranslationModelId) // Ensure unique typeId
class FieldTranslation extends HiveObject {
  @HiveField(0)
  final String? placeHolder;

  @HiveField(1)
  final String? fieldLabel;

  @HiveField(2)
  final String? subTitle;

  @HiveField(3)
  final String? helpTextFirstOption;

  @HiveField(4)
  final String? helpTextLastOption;

  @HiveField(5)
  final String? invalidFieldMessage;

  FieldTranslation({
    required this.placeHolder,
    required this.fieldLabel,
    required this.subTitle,
    required this.helpTextFirstOption,
    required this.helpTextLastOption,
    required this.invalidFieldMessage,
  });

  factory FieldTranslation.fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      throw ArgumentError("JSON data cannot be null");
    }

    return FieldTranslation(
      placeHolder: json["placeHolder"],
      fieldLabel: json["fieldLabel"],
      subTitle: json["subTitle"],
      helpTextFirstOption: json["helpTextFirstOption"],
      helpTextLastOption: json["helpTextLastOption"],
      invalidFieldMessage: json["invalidFieldMessage"],
    );
  }
}
