import 'package:hive/hive.dart';
import 'package:zonka_feedback/services/hive/hive_type_id.dart';

part 'heading_image.g.dart'; // This file will be generated by Hive

@HiveType(typeId: HiveTypeId.headingImageId)  // Ensure unique typeId
class HeadingImage extends HiveObject {
  @HiveField(0)
  final String path;

  @HiveField(1)
  final String id;

  @HiveField(2)
  final String companyId;

  HeadingImage({
    required this.path,
    required this.id,
    required this.companyId,
  });

  factory HeadingImage.fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      throw ArgumentError("JSON data cannot be null");
    }
    return HeadingImage(
      path: json["path"] ?? "",
      id: json["_id"] ?? '',
      companyId: json["companyId"] ?? "",
    );
  }
}
