import 'package:hive/hive.dart';
import 'package:zonka_feedback/services/hive/hive_type_id.dart';

part 'intro_page_translation.g.dart'; // This file will be generated by Hive


@HiveType(typeId: HiveTypeId.introPageTranslationModelId) // Assign a unique typeId for this class
class IntroPageTranslation extends HiveObject {
  @HiveField(0)
  final String? getStarted;

  @HiveField(1)
  final String? upperText;

  @HiveField(2)
  final String? bottomText;

  IntroPageTranslation({
    required this.getStarted,
    required this.upperText,
    required this.bottomText,
  });

  factory IntroPageTranslation.fromJson(Map<String, dynamic> json) {
    return IntroPageTranslation(
      getStarted: json["getStarted"],
      upperText: json["upperText"],
      bottomText: json["bottomText"],
    );
  }
}
