
import 'package:hive/hive.dart';
import 'package:zonka_feedback/services/hive/hive_type_id.dart';
part 'surveyId_model.g.dart'; // This file will be generated by Hive after running build_runner

@HiveType(typeId: HiveTypeId.surveyId) // Assign a unique typeId for SurveyId
class SurveyId extends HiveObject {
  @HiveField(0)
  final String? id;

  @HiveField(1)
  final String? name;

  @HiveField(2)
  final String? type;

  @HiveField(3)
  final String? description;

  @HiveField(4)
  final int? preMongifiedId;

  @HiveField(5)
  final String? viewMode;

  @HiveField(6)
  final String? mode;

  SurveyId({
    required this.id,
    required this.name,
    required this.type,
    required this.description,
    required this.preMongifiedId,
    required this.viewMode,
    required this.mode,
  });

  factory SurveyId.fromJson(Map<String, dynamic> json) => SurveyId(
        id: json["_id"] ?? '',
        name: json["name"] ?? '',
        type: json["type"] ?? '',
        description: json["description"] ?? '',
        preMongifiedId: json["pre_mongified_id"] ?? 0,
        viewMode: json["viewMode"] ?? '',
        mode: json["mode"] ?? "",
      );

  Map<String, dynamic> toJson() => {
        "_id": id,
        "name": name,
        "type": type,
        "description": description,
        "pre_mongified_id": preMongifiedId,
        "viewMode": viewMode,
        "mode": mode,
      };
}
