

import 'package:zonka_feedback/services/hive/hive_type_id.dart';
import 'package:zonka_feedback/template/data/data_model/template_industries_map.dart';
import 'package:zonka_feedback/template/data/data_model/template_model.dart';
import 'package:hive/hive.dart';

part 'template_mapping_model.g.dart'; // This will be generated by Hive after running build_runner

@HiveType(typeId: HiveTypeId.templateDataId) // Assign a unique typeId for TemplateData
class TemplateData extends HiveObject {
  @HiveField(0)
  final List<TemplateModel> templateModelList;

  @HiveField(1)
  final List<TemplateIndustriesMap> templateIndustriesMap;

  TemplateData({
    required this.templateModelList,
    required this.templateIndustriesMap,
  });
}
