
import 'package:zonka_feedback/services/hive/hive_type_id.dart';
import 'package:zonka_feedback/template/data/data_model/surveyId_model.dart';
import 'package:hive/hive.dart';
part 'template_model.g.dart'; // This will be generated by Hive after running the build command


@HiveType(typeId: HiveTypeId.templateModelId) // typeId must be unique for each Hive model
class TemplateModel extends HiveObject {
  @HiveField(0)
  final String? id;

  @HiveField(1)
  final List<String>? templateIndustries;

  @HiveField(2)
  final List<dynamic>? templateSubIndustries;

  @HiveField(3)
  final String? thumbnailImage;

  @HiveField(4)
  final List<String>? tags;

  @HiveField(5)
  final bool? isPopularTemplate;

  @HiveField(6)
  final bool? isActive;

  @HiveField(7)
  final String? refCode;

  @HiveField(8)
  final DateTime? createdDate;

  @HiveField(9)
  final SurveyId? surveyId;

  @HiveField(10)
  final int? fieldCount;

  @HiveField(11)
  final String? avgFillingTime;

  TemplateModel({
    required this.id,
    required this.templateIndustries,
    required this.templateSubIndustries,
    required this.thumbnailImage,
    required this.tags,
    required this.isPopularTemplate,
    required this.isActive,
    required this.refCode,
    required this.createdDate,
    required this.surveyId,
    required this.fieldCount,
    required this.avgFillingTime,
  });

  factory TemplateModel.fromJson(Map<String, dynamic> json) => TemplateModel(
        id: json["_id"],
        templateIndustries: json["templateIndustries"] != null
            ? List<String>.from(json["templateIndustries"].map((x) => x))
            : [],
        templateSubIndustries: json["templateSubIndustries"] != null
            ? List<dynamic>.from(json["templateSubIndustries"].map((x) => x))
            : [],
        thumbnailImage: json["thumbnailImage"] ?? "",
        tags: json["tags"] != null
            ? List<String>.from(json["tags"].map((x) => x))
            : [],
        isPopularTemplate: json["isPopularTemplate"],
        isActive: json["isActive"] ?? false,
        refCode: json["refCode"],
        createdDate: json["createdDate"] != null
            ? DateTime.parse(json["createdDate"])
            : DateTime.now(),
        surveyId: json["surveyId"] != null
            ? SurveyId.fromJson(json["surveyId"])
            : null,
        fieldCount: json['fieldsCount'] ?? 0,
        avgFillingTime: json["avgFillingTime"].toString(),
      );

  Map<String, dynamic> toJson() => {
        "_id": id,
        "templateIndustries": templateIndustries != null
            ? List<dynamic>.from(templateIndustries!.map((x) => x))
            : [],
        "templateSubIndustries":
            List<dynamic>.from(templateSubIndustries!.map((x) => x)),
        "thumbnailImage": thumbnailImage,
        "tags": List<dynamic>.from(tags!.map((x) => x)),
        "isPopularTemplate": isPopularTemplate,
        "isActive": isActive,
        "refCode": refCode,
        "createdDate": createdDate?.toIso8601String(),
      };
}

